name: reloop

settings:
  MARKETING_VERSION: "2.0"
  base:
    DEVELOPMENT_TEAM: FHURMLY499
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  reloop:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: reloop
        excludes:
          - old/**
    info:
      path: reloop/Info.plist
      properties:
        CFBundleDisplayName: ReLoop
        LSApplicationCategoryType: public.app-category.adventure-games
        UILaunchScreen: {}
        UIRequiresFullScreen: YES
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.tuildes.reloop
